version: 2
jobs:
  build:
    docker:
      - image: node:12.13.0

      - image: mongo:3.6.3
        command: [mongod, --smallfiles]
        # some containers require setting environment variables

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json"}}
      - run:
          command: npm test
